In [77]:
import pandas as pd

In [78]:
dataset=pd.read_csv("insurance_pre.csv")

In [79]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [80]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [81]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [82]:
dependent=dataset[["charges"]]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [83]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [85]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [86]:
weight=regressor.coef_
weight

array([[  255.00393413,   319.72092521,   434.84826239,   -24.03756306,
        23600.10822772]])

In [87]:
bias=regressor.intercept_
bias

array([-11723.1972154])

In [88]:
Y_Pred=regressor.predict(X_test)
Y_Pred

array([[11539.44581528],
       [ 9968.74278246],
       [37751.59582096],
       [15957.40036179],
       [ 7036.98007928],
       [ 3637.03841156],
       [ 1179.61765452],
       [14096.50152026],
       [ 8863.12482524],
       [ 7373.78064844],
       [ 4326.17891137],
       [10209.44007162],
       [ 8948.72704592],
       [ 4365.23481612],
       [27690.16557682],
       [11283.73018443],
       [11226.3034747 ],
       [ 5548.7853782 ],
       [ 8084.51807457],
       [26544.57988829],
       [33401.07281999],
       [13977.51015291],
       [11128.63511595],
       [32494.56089736],
       [ 4413.64230448],
       [ 8677.41360906],
       [  852.16866897],
       [10332.29546914],
       [ 4174.94787306],
       [10189.26653873],
       [ 8733.69084308],
       [40441.51175927],
       [15892.68337072],
       [14107.65583177],
       [24391.42393578],
       [ 4559.38578935],
       [13002.03787455],
       [30937.78517503],
       [33177.83450926],
       [ 3927.67199927],
       [ 3531.64199247],
       [ 4280.34429215],
       [30110.77093601],
       [39022.75146147],
       [27976.93513436],
       [ 4732.65153298],
       [10964.00925922],
       [ 7710.52277309],
       [ 3075.90850048],
       [10600.45657254],
       [ 5012.40472689],
       [ 3058.88730104],
       [33480.09645604],
       [38016.33067319],
       [16175.58889809],
       [ 6583.10775971],
       [ 6073.09989144],
       [ 9315.70598377],
       [ 9385.19883157],
       [11661.15173709],
       [ 2050.02587602],
       [38559.28990913],
       [15408.33658877],
       [12103.72805982],
       [13422.57949197],
       [14185.96777111],
       [26289.57595416],
       [31933.0516518 ],
       [ 1215.72135565],
       [ 9783.94339283],
       [12784.22867274],
       [11855.30271032],
       [25585.41711266],
       [15852.0039427 ],
       [11250.34103776],
       [12209.5038134 ],
       [ 7016.80654639],
       [ 9934.26260459],
       [29739.92796798],
       [39352.91500148],
       [11509.20900207],
       [37549.24273984],
       [ 4093.92137927],
       [ 9754.41827634],
       [34123.40233663],
       [29385.72686491],
       [ 8770.03219337],
       [ 4794.21619059],
       [12365.31057859],
       [30693.2238557 ],
       [ 9571.14769691],
       [11549.88843008],
       [ 7760.45907164],
       [ 9254.14132616],
       [ 7793.41043931],
       [ 6783.12562086],
       [35469.71758301],
       [33534.37083231],
       [ 7282.69087433],
       [15321.82254154],
       [ 4348.9253134 ],
       [ 8418.54564476],
       [ 6837.39999713],
       [31903.5265353 ],
       [32819.76937601],
       [ 1876.04843568],
       [ 9566.84588774],
       [ 6287.42439756],
       [13913.50485854],
       [37384.17910411],
       [10065.69944449],
       [10840.30047966],
       [ 9904.02579138],
       [26354.29294524],
       [40251.22481621],
       [ 8145.37103548],
       [  821.55252127],
       [ 9315.70598377],
       [15562.5198307 ],
       [ 9280.5141092 ],
       [35312.81978663],
       [ 7291.98401342],
       [17066.17065247],
       [ 9037.10226557],
       [ 8564.28912963],
       [ 2936.03190352],
       [32609.68823454],
       [31231.60736476],
       [39622.22558059],
       [ 5117.80114598],
       [ 9638.57924244],
       [ 3828.47483033],
       [ 7993.42830046],
       [ 8291.82621706],
       [32154.66643926],
       [30114.63496618],
       [30236.34088799],
       [ 9250.27729599],
       [32860.82813851],
       [ 3185.16894974],
       [ 3288.23014885],
       [10910.44657966],
       [13447.32875175],
       [12254.04727158],
       [ 5350.7703748 ],
       [15787.28695163],
       [15266.83646855],
       [ 2365.17107435],
       [ -188.02060046],
       [10450.84905749],
       [ 7034.26552482],
       [32166.25852977],
       [11923.88373157],
       [ 2869.3120547 ],
       [ 6025.8418788 ],
       [ 8183.71524351],
       [ 4209.04871645],
       [ 2549.59112948],
       [11283.73018443],
       [12117.32300809],
       [ 6673.48583711],
       [16532.12522114],
       [11570.06196297],
       [14161.93020805],
       [ 2831.34718114],
       [ 6663.04322231],
       [23436.12519032],
       [ 7078.09728629],
       [ 4905.4794976 ],
       [ 5335.98968227],
       [ 6558.35849993],
       [ 4575.31595759],
       [ 9703.29623352],
       [ 5563.09202317],
       [ 6034.04398669],
       [ 6918.04715645],
       [ 3296.43225674],
       [ 5346.90634462],
       [37474.55718151],
       [ 1155.58009146],
       [12318.05256595],
       [ 8584.08332804],
       [13658.50092441],
       [ 5688.66197515],
       [ 4826.45586155],
       [35975.86142111],
       [ 3774.20045406],
       [ 2379.47771932],
       [14828.12417599],
       [12192.48261396],
       [34514.41883755],
       [ 5048.50842802],
       [ 5884.81580613],
       [31766.3644928 ],
       [ 5818.0959573 ],
       [ 2365.88277106],
       [ 7829.51414044],
       [ 9506.43070583],
       [ 8347.25006905],
       [ 5544.92134803],
       [12712.93309704],
       [38723.91576586],
       [13402.78529356],
       [29055.56332489],
       [ 6428.92451778],
       [35806.89748666],
       [ 3170.86230476],
       [12383.48125373],
       [ 9261.8693865 ],
       [ 6590.83582005],
       [11158.87192916],
       [13998.39538251],
       [ 5034.20178304],
       [ 4692.68380168],
       [ 8094.96068937],
       [ 1726.44092063],
       [ 7369.91661827],
       [ 4160.64122809],
       [13259.04466643],
       [ 4016.90060096],
       [10400.87649039],
       [ 6880.08228289],
       [ 9469.17752899],
       [ 2005.48241783],
       [13617.82149639],
       [16402.69123899],
       [15256.39385375],
       [11060.0540947 ],
       [ 5961.59893527],
       [ 2620.88670519],
       [ 2434.4637923 ],
       [12886.91053737],
       [14512.26728095],
       [ 4517.61533014],
       [ 4225.35821917],
       [ 9808.69265261],
       [ 9584.30486617],
       [27884.31655004],
       [ 7329.94888697],
       [10015.28909839],
       [ 6599.41726243],
       [29447.72930152],
       [11431.33484173],
       [ 7234.99508268],
       [10114.10693285],
       [12114.17067463],
       [ 2470.56749343],
       [10547.33167198],
       [ 1240.47061543],
       [ 6496.35606332],
       [28914.06320467],
       [39042.92499436],
       [ 6647.11305407],
       [ 8515.02825924],
       [ 2138.78043016],
       [ -123.30360939],
       [10713.58105197],
       [ 4376.82690664],
       [ 4680.00067997],
       [ 2950.33854849],
       [ 7426.905549  ],
       [33694.42096216],
       [37894.18697238],
       [14548.37098208],
       [ 8094.96068937],
       [15576.82647568],
       [33300.68990678],
       [ 8960.79318398]])

In [89]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_Pred)
r_score

0.7974504524086945

In [90]:
import pickle
filename="finalized_MLR_Assignment.sav"
pickle.dump(regressor, open(filename,'wb'))

In [91]:
loaded_model=pickle.load(open("finalized_MLR_Assignment.sav",'rb'))
result=loaded_model.predict([[40,30,2,1,1]])
#result=loaded_model.predict([[1,21,3,0,0]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [75]:
result

array([[32514.35509577]])

In [106]:
loaded_model=pickle.load(open("finalized_MLR_Assignment.sav",'rb'))
result=loaded_model.predict([[52,30.2,1,1,0]])
result

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[11603.39000032]])

In [107]:
X_test, Y_test, Y_Pred

(      age  bmi  children  sex_male  smoker_yes
 578    52   30         1         1           0
 610    47   29         1         0           0
 569    48   40         2         1           1
 1034   61   38         0         1           0
 198    51   18         0         0           0
 ...   ...  ...       ...       ...         ...
 1084   62   30         2         0           0
 726    41   28         1         1           0
 1132   57   40         0         1           0
 725    30   39         3         0           1
 963    46   24         3         1           0

 [268 rows x 5 columns],
       charges
 578      9724
 610      8547
 569     45702
 1034    12950
 198      9644
 ...       ...
 1084    15019
 726      6664
 1132    20709
 725     40932
 963      9500

 [268 rows x 1 columns],
 array([[11539.44581528],
        [ 9968.74278246],
        [37751.59582096],
        [15957.40036179],
        [ 7036.98007928],
        [ 3637.03841156],
        [ 1179.61765452],
        [14096.50152026],
        [ 8863.12482524],
        [ 7373.78064844],
        [ 4326.17891137],
        [10209.44007162],
        [ 8948.72704592],
        [ 4365.23481612],
        [27690.16557682],
        [11283.73018443],
        [11226.3034747 ],
        [ 5548.7853782 ],
        [ 8084.51807457],
        [26544.57988829],
        [33401.07281999],
        [13977.51015291],
        [11128.63511595],
        [32494.56089736],
        [ 4413.64230448],
        [ 8677.41360906],
        [  852.16866897],
        [10332.29546914],
        [ 4174.94787306],
        [10189.26653873],
        [ 8733.69084308],
        [40441.51175927],
        [15892.68337072],
        [14107.65583177],
        [24391.42393578],
        [ 4559.38578935],
        [13002.03787455],
        [30937.78517503],
        [33177.83450926],
        [ 3927.67199927],
        [ 3531.64199247],
        [ 4280.34429215],
        [30110.77093601],
        [39022.75146147],
        [27976.93513436],
        [ 4732.65153298],
        [10964.00925922],
        [ 7710.52277309],
        [ 3075.90850048],
        [10600.45657254],
        [ 5012.40472689],
        [ 3058.88730104],
        [33480.09645604],
        [38016.33067319],
        [16175.58889809],
        [ 6583.10775971],
        [ 6073.09989144],
        [ 9315.70598377],
        [ 9385.19883157],
        [11661.15173709],
        [ 2050.02587602],
        [38559.28990913],
        [15408.33658877],
        [12103.72805982],
        [13422.57949197],
        [14185.96777111],
        [26289.57595416],
        [31933.0516518 ],
        [ 1215.72135565],
        [ 9783.94339283],
        [12784.22867274],
        [11855.30271032],
        [25585.41711266],
        [15852.0039427 ],
        [11250.34103776],
        [12209.5038134 ],
        [ 7016.80654639],
        [ 9934.26260459],
        [29739.92796798],
        [39352.91500148],
        [11509.20900207],
        [37549.24273984],
        [ 4093.92137927],
        [ 9754.41827634],
        [34123.40233663],
        [29385.72686491],
        [ 8770.03219337],
        [ 4794.21619059],
        [12365.31057859],
        [30693.2238557 ],
        [ 9571.14769691],
        [11549.88843008],
        [ 7760.45907164],
        [ 9254.14132616],
        [ 7793.41043931],
        [ 6783.12562086],
        [35469.71758301],
        [33534.37083231],
        [ 7282.69087433],
        [15321.82254154],
        [ 4348.9253134 ],
        [ 8418.54564476],
        [ 6837.39999713],
        [31903.5265353 ],
        [32819.76937601],
        [ 1876.04843568],
        [ 9566.84588774],
        [ 6287.42439756],
        [13913.50485854],
        [37384.17910411],
        [10065.69944449],
        [10840.30047966],
        [ 9904.02579138],
        [26354.29294524],
        [40251.22481621],
        [ 8145.37103548],
        [  821.55252127],
        [ 9315.70598377],
        [15562.5198307 ],
        [ 9280.5141092 ],
        [35312.81978663],
        [ 7291.98401342],
        [17066.17065247],
        [ 9037.10226557],
        [ 8564.28912963],
        [ 2936.03190352],
        [32609.68823454],
        [31231.60736476],
        [39622.22558059],
        [ 5117.80114598],
        [ 9638.57924244],
        [ 3828.47483033],
        [ 7993.42830046],
        [ 8291.82621706],
        [32154.66643926],
        [30114.63496618],
        [30236.34088799],
        [ 9250.27729599],
        [32860.82813851],
        [ 3185.16894974],
        [ 3288.23014885],
        [10910.44657966],
        [13447.32875175],
        [12254.04727158],
        [ 5350.7703748 ],
        [15787.28695163],
        [15266.83646855],
        [ 2365.17107435],
        [ -188.02060046],
        [10450.84905749],
        [ 7034.26552482],
        [32166.25852977],
        [11923.88373157],
        [ 2869.3120547 ],
        [ 6025.8418788 ],
        [ 8183.71524351],
        [ 4209.04871645],
        [ 2549.59112948],
        [11283.73018443],
        [12117.32300809],
        [ 6673.48583711],
        [16532.12522114],
        [11570.06196297],
        [14161.93020805],
        [ 2831.34718114],
        [ 6663.04322231],
        [23436.12519032],
        [ 7078.09728629],
        [ 4905.4794976 ],
        [ 5335.98968227],
        [ 6558.35849993],
        [ 4575.31595759],
        [ 9703.29623352],
        [ 5563.09202317],
        [ 6034.04398669],
        [ 6918.04715645],
        [ 3296.43225674],
        [ 5346.90634462],
        [37474.55718151],
        [ 1155.58009146],
        [12318.05256595],
        [ 8584.08332804],
        [13658.50092441],
        [ 5688.66197515],
        [ 4826.45586155],
        [35975.86142111],
        [ 3774.20045406],
        [ 2379.47771932],
        [14828.12417599],
        [12192.48261396],
        [34514.41883755],
        [ 5048.50842802],
        [ 5884.81580613],
        [31766.3644928 ],
        [ 5818.0959573 ],
        [ 2365.88277106],
        [ 7829.51414044],
        [ 9506.43070583],
        [ 8347.25006905],
        [ 5544.92134803],
        [12712.93309704],
        [38723.91576586],
        [13402.78529356],
        [29055.56332489],
        [ 6428.92451778],
        [35806.89748666],
        [ 3170.86230476],
        [12383.48125373],
        [ 9261.8693865 ],
        [ 6590.83582005],
        [11158.87192916],
        [13998.39538251],
        [ 5034.20178304],
        [ 4692.68380168],
        [ 8094.96068937],
        [ 1726.44092063],
        [ 7369.91661827],
        [ 4160.64122809],
        [13259.04466643],
        [ 4016.90060096],
        [10400.87649039],
        [ 6880.08228289],
        [ 9469.17752899],
        [ 2005.48241783],
        [13617.82149639],
        [16402.69123899],
        [15256.39385375],
        [11060.0540947 ],
        [ 5961.59893527],
        [ 2620.88670519],
        [ 2434.4637923 ],
        [12886.91053737],
        [14512.26728095],
        [ 4517.61533014],
        [ 4225.35821917],
        [ 9808.69265261],
        [ 9584.30486617],
        [27884.31655004],
        [ 7329.94888697],
        [10015.28909839],
        [ 6599.41726243],
        [29447.72930152],
        [11431.33484173],
        [ 7234.99508268],
        [10114.10693285],
        [12114.17067463],
        [ 2470.56749343],
        [10547.33167198],
        [ 1240.47061543],
        [ 6496.35606332],
        [28914.06320467],
        [39042.92499436],
        [ 6647.11305407],
        [ 8515.02825924],
        [ 2138.78043016],
        [ -123.30360939],
        [10713.58105197],
        [ 4376.82690664],
        [ 4680.00067997],
        [ 2950.33854849],
        [ 7426.905549  ],
        [33694.42096216],
        [37894.18697238],
        [14548.37098208],
        [ 8094.96068937],
        [15576.82647568],
        [33300.68990678],
        [ 8960.79318398]]))

In [105]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')