In [126]:
# Importing pandas library
import pandas as pd

In [127]:
# Read the dataset
dataset=pd.read_csv("insurance_pre.csv")

In [128]:
# display the dataset
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [129]:
# Handle categorical data
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [130]:
# Display the columns in the dataset
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [131]:
# Assign input values
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [132]:
# Assign output values
dependent=dataset[["charges"]]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [133]:
# Split training and test data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [134]:
#Standardization

In [135]:
X_train

      age  bmi  children  sex_male  smoker_yes
621    37   34         4         1           1
194    18   34         0         1           0
240    23   36         2         0           1
1168   32   35         2         1           0
1192   58   32         1         0           0
...   ...  ...       ...       ...         ...
763    27   26         0         1           0
835    42   35         2         1           0
1216   40   25         0         1           0
559    19   35         0         1           0
684    33   18         1         0           0

[1070 rows x 5 columns]

In [136]:
# Applying standardization (preprocessing) for input training and test data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train_pre=sc.fit_transform(X_train) 
X_test_pre=sc.transform(X_test) # No need to use fit_transform for preprocessing input test data since the sc variable is already holding the preprocessing logic.

In [137]:
X_train, X_train_pre, X_test, X_test_pre # Values are changed to defined range from -1 to 1 as standardized value

(      age  bmi  children  sex_male  smoker_yes
 621    37   34         4         1           1
 194    18   34         0         1           0
 240    23   36         2         0           1
 1168   32   35         2         1           0
 1192   58   32         1         0           0
 ...   ...  ...       ...       ...         ...
 763    27   26         0         1           0
 835    42   35         2         1           0
 1216   40   25         0         1           0
 559    19   35         0         1           0
 684    33   18         1         0           0

 [1070 rows x 5 columns],
 array([[-0.14853305,  0.60616004,  2.41394802,  1.01506676,  1.97125461],
        [-1.49780784,  0.60616004, -0.89219519,  1.01506676, -0.50729114],
        [-1.14273553,  0.92836135,  0.76087642, -0.98515688,  1.97125461],
        ...,
        [ 0.06451033, -0.84374587, -0.89219519,  1.01506676, -0.50729114],
        [-1.42679338,  0.7672607 , -0.89219519,  1.01506676, -0.50729114],
        [-0.4325909 , -1.97145047, -0.06565939, -0.98515688, -0.50729114]],
       shape=(1070, 5)),
       age  bmi  children  sex_male  smoker_yes
 578    52   30         1         1           0
 610    47   29         1         0           0
 569    48   40         2         1           1
 1034   61   38         0         1           0
 198    51   18         0         0           0
 ...   ...  ...       ...       ...         ...
 1084   62   30         2         0           0
 726    41   28         1         1           0
 1132   57   40         0         1           0
 725    30   39         3         0           1
 963    46   24         3         1           0

 [268 rows x 5 columns],
 array([[ 0.91668389, -0.03824259, -0.06565939,  1.01506676, -0.50729114],
        [ 0.56161157, -0.19934324, -0.06565939, -0.98515688, -0.50729114],
        [ 0.63262604,  1.57276398,  0.76087642,  1.01506676,  1.97125461],
        ...,
        [ 1.2717562 ,  1.57276398, -0.89219519,  1.01506676, -0.50729114],
        [-0.64563429,  1.41166332,  1.58741222, -0.98515688,  1.97125461],
        [ 0.49059711, -1.00484653,  1.58741222,  1.01506676, -0.50729114]],
       shape=(268, 5)))

In [115]:
# Creating model after standardization

In [116]:
# Using SVM regression algorithm to train the Preprocessed input and Original output
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)  
regressor.fit(X_train_pre, Y_train)  # X_train is preprocessed data, Y_train is original data without any preprocessing

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000)

In [138]:
# Prediction based on preprocessed input test data
Y_Pred=regressor.predict(X_test_pre)
Y_Pred

array([10189.50183286,  8848.49384476, 40895.5064764 , 12668.48547368,
       10405.71129613,  4093.03087946,  2275.76154843, 11429.39263349,
        7186.46305574,  5069.87948751,  7386.71577115, 10531.74487347,
        7550.08740833,  4366.99586107, 23420.35134702, 11190.70474912,
       12450.45097817,  2923.69165401,  6444.8670852 , 24116.46735057,
       24271.02382659, 12879.69749279, 10088.65582567, 28037.32728648,
        1830.46950591,  3797.18987254,  4422.83001808,  7716.21585582,
        3898.77600295,  8524.15326141,  7832.61296669, 36969.82653281,
       13049.50744754, 10522.80148605, 14413.66484153,  3685.69973653,
        8463.8627991 , 37733.74187667, 35578.43870485,  2190.70045844,
        5633.21256425,  2979.58959225, 23729.1308547 , 38763.79412848,
       29440.01517482,  3821.49426123, 11183.77072329,  6857.98442668,
        4038.25933635, 12181.9943767 ,  2406.46396331,  4646.68274393,
       30795.45325789, 34253.25737736, 12089.92451002,  2601.74903582,
        2278.53730281,  8963.39327622,  9561.62228136, 12949.11794985,
        1725.64804421, 29429.32166193, 14142.27679438, 10163.79257692,
       10370.36523816, 10108.41417825, 23753.90803284, 32404.13473988,
        4113.64745954,  7712.42474539, 13240.58801417, 12002.60673495,
       19790.70937678, 13886.89995065, 12927.79763864, 12899.91645661,
        7662.01174759,  8201.31178822, 23609.82201778, 37886.19838662,
       11503.44345894, 31376.92208179,  1856.31847653,  7781.42637244,
       39993.50307452, 22288.61978541,  3669.58101971,  2394.50117982,
       12712.66986177, 34224.48216566,  5774.49084137, 10696.71805952,
        3101.56500119,  8877.23740114,  3901.70498381,  4586.70255552,
       31726.73220337, 33725.93931031,  5102.1199092 , 10858.03178734,
        1957.77706357,  4984.3718235 ,  4540.65428952, 35049.13467655,
       27245.68892895,  3355.13410573, 11083.93598611,  3139.17601741,
       11693.08559804, 33012.39926672, 12433.58503296,  5007.92951887,
        9156.52511245, 24752.16450598, 36783.63780376,  7649.68454352,
        2019.02567235,  8963.39327622, 12549.55463115,  9399.85548458,
       36014.04119453, 10726.77765039, 14070.05121514,  5089.87756841,
        7803.31450006,  5059.30242166, 27736.66093958, 20591.10913215,
       34496.79199985,  1777.92598193,  8596.28154731,  2178.29486957,
        6097.60509345,  9361.86248967, 30900.53596832, 28936.46855312,
       21608.86130916, 10460.03942636, 22881.19674369,  2490.28977622,
        2252.71465202, 10717.70311082,  9571.25460334, 10270.77143734,
        4537.76429895, 14223.27510851, 13149.6712841 ,  4039.04691857,
        1830.5678594 , 10898.70627151,  6017.22883825, 33282.90038368,
        9768.71941102,  2190.08395263,  2810.67655868,  6646.11439088,
        2439.64896653,  2177.2626046 , 11190.70474912, 10071.21486736,
        4468.80070959, 12976.70281429, 12912.26764325,  9440.46970992,
        4468.4660238 ,  5101.83953026, 14385.73947869,  5522.90638029,
        3859.90708753,  2411.84405465,  3960.29282321,  4147.76809389,
        8289.13046515,  2014.67871021,  4450.8753788 ,  5138.84631913,
        4124.66460814,  5844.38656816, 28957.97433934,  1691.02605522,
       11407.00523595,  6464.82530399, 11324.87761667,  2483.65565336,
        5418.40294753, 26459.92588649,  1884.73941843,  2780.17893574,
       14246.9935067 , 10329.76522556, 33140.75029311,  4297.05959595,
        5408.32571813, 22979.59495133,  2138.78436559,  2116.28679526,
        6174.23920875,  5920.37717974,  4165.6966562 ,  3931.28336858,
       11388.55099335, 32524.00489301, 12513.83467103, 20512.09502422,
        4331.60987793, 41744.28732608,  3644.6217011 ,  9488.58763699,
        5912.32257197,  3320.02365906,  8706.67337992, 13595.74970082,
        5238.76001144,  2437.72952164,  6571.40252629,  2095.24963309,
        6306.87620719,  4641.13863197, 14226.13296188,  7293.79785973,
        6224.89965692,  7862.0262364 ,  8709.26837207,  2891.24019116,
       12231.1001642 , 13726.82146782, 12720.70210496, 12231.75425598,
        7333.93209726,  2250.98188612,  1672.92724419,  7662.07851209,
       12572.44348081,  5564.34794125,  4396.15332871,  7183.28655491,
        9124.00997223, 27077.97060075,  5701.44473385, 11457.28372   ,
        5625.23537287, 28619.01087261,  7505.7024298 ,  7123.72795032,
        8255.21775432, 10528.97169111,  3271.25282146,  7551.21553859,
        2567.73613638,  6473.04833351, 26736.04116445, 34044.39777189,
        4233.09981146,  3576.80406225,  2225.93899063,  1746.3013947 ,
        7641.74190342,  2123.09014977,  5061.19677547,  3426.60210489,
        9434.12000599, 29944.95875046, 32489.10146578, 14880.98147245,
        6571.40252629, 11212.49344689, 31475.24873033,  9442.36799443])

In [139]:
# Evaluate performance 
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,Y_Pred)
r_score

0.8252164693926967

In [140]:
# Import library to save Python objects to a file and load them 
import pickle
filename="finalized_model_svr.sav"

In [141]:
pickle.dump(regressor, open(filename,'wb'))

In [142]:
# Preprocessing user input using already trained input data
preinput=sc.transform([[52,30.2,1,1,0]])
preinput

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[ 0.91668389, -0.00602245, -0.06565939,  1.01506676, -0.50729114]])

In [143]:
loaded_model=pickle.load(open("finalized_model_svr.sav", 'rb'))
result=loaded_model.predict(preinput)
result

array([10185.15295002])

In [144]:
X_test, X_test_pre, Y_test # checking the prediction for input row 52 from test

(      age  bmi  children  sex_male  smoker_yes
 578    52   30         1         1           0
 610    47   29         1         0           0
 569    48   40         2         1           1
 1034   61   38         0         1           0
 198    51   18         0         0           0
 ...   ...  ...       ...       ...         ...
 1084   62   30         2         0           0
 726    41   28         1         1           0
 1132   57   40         0         1           0
 725    30   39         3         0           1
 963    46   24         3         1           0

 [268 rows x 5 columns],
 array([[ 0.91668389, -0.03824259, -0.06565939,  1.01506676, -0.50729114],
        [ 0.56161157, -0.19934324, -0.06565939, -0.98515688, -0.50729114],
        [ 0.63262604,  1.57276398,  0.76087642,  1.01506676,  1.97125461],
        ...,
        [ 1.2717562 ,  1.57276398, -0.89219519,  1.01506676, -0.50729114],
        [-0.64563429,  1.41166332,  1.58741222, -0.98515688,  1.97125461],
        [ 0.49059711, -1.00484653,  1.58741222,  1.01506676, -0.50729114]],
       shape=(268, 5)),
       charges
 578      9724
 610      8547
 569     45702
 1034    12950
 198      9644
 ...       ...
 1084    15019
 726      6664
 1132    20709
 725     40932
 963      9500

 [268 rows x 1 columns])